### ISSUE TITLE
Extraneous escaping of hyphenated qname prefixes

### ISSUE THREAD

**Issue by ijdickinson** [atextor/owl-cli#3]
Nice job on `owl write`! A very useful tool to have around.

I was, however, surprised to see some unexpected quoting of hyphens in the result:

## Test case

```sh
 $ echo '@prefix foo-bar: <http://foo.com/bar>  foo-bar:s foo-bar:p 42' | owl write -
```

## Expected result

```turtle
@prefix foo-bar: <http://foo.com/bar> .

foo-bar:s foo-bar:p 42 .
```

## Actual result

```turtle
@prefix foo-bar: <http://foo.com/bar> .

foo\-bar:s foo\-bar:p 42 .
```

As far as I know, `foo-bar` is a legal prefix name in Turtle, without needing the hyphen to be protected. Is this a writer bug, or
is there an option I should be setting to prevent this escaping?

## Version info

```sh
$ owl --version ; java --version ; lsb_release -a
owl-cli version: snapshot build date: 2022-01-25 06:17:26
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by atextor** [comment]
Hi @ijdickinson!
Thanks for reporting this. This is most certainly a bug. Currently I'm on vacation and AFK (except mobile phone :-D) but afterwards I'll have a look.

**Comment by ijdickinson** [comment]
@alextor Thanks! No hurry - I have a workaround using `sed` for the time being. Enjoy your vacation :smile:

**Comment by atextor** [comment]
I've taken a look at the spec, and in the description of [what should be escaped](https://www.w3.org/TR/turtle/#sec-escapes) and how IRIs should be written, it's a bit vague on prefix, it says:

> Prefixed names are a superset of XML QNames. They differ in that the local part of prefixed
> names may include:
>
> * leading digits, e.g. leg:3032571 or isbn13:9780136019701
> * non leading colons, e.g. og:video:height
> * [reserved character escape sequences](https://www.w3.org/TR/turtle/#reserved), e.g. wgs:lat\-long

No statement is made about the prefix part of prefixed names itself.
But the [grammar](https://www.w3.org/TR/turtle/#sec-grammar-grammar) clarifies it of course:

> `PN_CHARS_BASE | ::= | [A-Z] |  [a-z] |  [#x00C0-#x00D6] |  [#x00D8-#x00F6] |  [#x00F8-#x02FF] |  [#x0370-#x037D] |  [#x037F-#x1FFF] |  [#x200C-#x200D] |  [#x2070-#x218F] |  [#x2C00-#x2FEF] |  [#x3001-#xD7FF] |  [#xF900-#xFDCF] |  [#xFDF0-#xFFFD] |  [#x10000-#xEFFFF]`
> `PN_CHARS_U | ::= | PN_CHARS_BASE |  '_'`
> `PN_CHARS | ::= | PN_CHARS_U |  '-' |  [0-9] |  #x00B7 |  [#x0300-#x036F] | [#x203F-#x2040]`
> `PN_PREFIX | ::= | PN_CHARS_BASE ((PN_CHARS |  '.')* PN_CHARS)?`

I.e., a prefix must start with a regular letter (included accented) but may be followed by dash, underscores, numbers etc.

I've opened a corresponding issue (linked above this post) in the _turtle-formatter_, the project that contains the relevant code.

**Comment by atextor** [comment]
The issue is fixed in owl-cli [1.2.1](https://github.com/atextor/owl-cli/releases/tag/v1.2.1).

**Comment by ijdickinson** [comment]
Thanks @atextor. I agree that the simplified case that I presented in the original report is now working. Unfortunately, when I tried the 1.2.1 release on my actual code, I'm still seeing some escaped `-` characters.

## Input

```sh
ian@alder $ cat generated-output.ttl 
@prefix void:  <http://rdfs.org/ns/void#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix org:   <http://www.w3.org/ns/org#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix version: <http://purl.org/linked-data/version#> .
@prefix qb:    <http://purl.org/linked-data/cube#> .
@prefix condition: <http://verna.earth/def/natural_england/metric/3.1/habitat/condition/> .
@prefix at:    <http://environment.data.gov.uk/public-register/def/applicant-type/> .
@prefix dct:   <http://purl.org/dc/terms/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix reg:   <http://purl.org/linked-data/registry#> .
@prefix time:  <http://www.w3.org/2006/time#> .
@prefix api:   <http://purl.org/linked-data/api/vocab#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

condition:condition-assessment-n-a
        a                condition:ConditionCategory ;
        condition:score  1.0 ;
        skos:prefLabel   "Condition Assessment N/A"@en .

condition:fairly-poor
        a                condition:ConditionCategory ;
        condition:score  1.5 ;
        skos:prefLabel   "Fairly Poor"@en .

condition:fairly-good
        a                condition:ConditionCategory ;
        condition:score  2.5 ;
        skos:prefLabel   "Fairly Good"@en .

condition:poor  a        condition:ConditionCategory ;
        condition:score  1.0 ;
        skos:prefLabel   "Poor"@en .

condition:good  a        condition:ConditionCategory ;
        condition:score  3.0 ;
        skos:prefLabel   "Good"@en .

condition:n-a-other  a   condition:ConditionCategory ;
        condition:score  0.0 ;
        skos:prefLabel   "N/A - Other"@en .

condition:conditionCategories
        a                   skos:ConceptScheme ;
        skos:hasTopConcept  condition:n-a-other , condition:condition-assessment-n-a , condition:poor , condition:fairly-poor , condition:moderate , condition:fairly-good , condition:good ;
        skos:prefLabel      "A concept scheme for BNG Metric 3.1 condition categories."@en .

condition:moderate  a    condition:ConditionCategory ;
        condition:score  2.0 ;
        skos:prefLabel   "Moderate"@en .
```

## Output

```sh
ian@alder $ owl write generated-output.ttl 
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix condition: <http://verna.earth/def/natural_england/metric/3.1/habitat/condition/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

condition:condition\-assessment\-n\-a a condition:ConditionCategory ;
  condition:score 1.0 ;
  skos:prefLabel "Condition Assessment N/A"@en .

condition:conditionCategories a skos:ConceptScheme ;
  skos:hasTopConcept condition:condition\-assessment\-n\-a ;
  skos:hasTopConcept condition:fairly\-good ;
  skos:hasTopConcept condition:fairly\-poor ;
  skos:hasTopConcept condition:good ;
  skos:hasTopConcept condition:moderate ;
  skos:hasTopConcept condition:n\-a\-other ;
  skos:hasTopConcept condition:poor ;
  skos:prefLabel "A concept scheme for BNG Metric 3.1 condition categories."@en .

condition:fairly\-good a condition:ConditionCategory ;
  condition:score 2.5 ;
  skos:prefLabel "Fairly Good"@en .

condition:fairly\-poor a condition:ConditionCategory ;
  condition:score 1.5 ;
  skos:prefLabel "Fairly Poor"@en .

condition:good a condition:ConditionCategory ;
  condition:score 3.0 ;
  skos:prefLabel "Good"@en .

condition:moderate a condition:ConditionCategory ;
  condition:score 2.0 ;
  skos:prefLabel "Moderate"@en .

condition:n\-a\-other a condition:ConditionCategory ;
  condition:score 0.0 ;
  skos:prefLabel "N/A - Other"@en .

condition:poor a condition:ConditionCategory ;
  condition:score 1.0 ;
  skos:prefLabel "Poor"@en .
```

Just for confirmation:

```sh
ian@alder $ owl --version
owl-cli version: 1.2.1 build date: 2022-09-19 03:47:55
```

I don't have a good encapsulation for why the extracted example is fixed but the larger example not, but hopefully the examples above will help.

**Comment by atextor** [comment]
Thanks! In your initial example, the dash was in the prefix part (before the `:`), while in your second example, it's in the local name part (after the `:`).
According to the spec, the prefix part may contain dashes which may not be escaped. This is what is fixed now.

_However_ as it turns out (as I read the spec and the grammar rules again), in the local name part, `-`, `_` and `.` are allowed _both_ escaped and unescaped, while the other special characters (e.g. `(`, `)`, `,`, `;`, ...) are allowed only in the escaped form.

So _technically_ the current version with escaped dashes in the local name after the colon is correct, and it's even written like this in the spec:
![image](https://user-images.githubusercontent.com/1199036/191160460-af801538-ae85-407d-9340-40d3ff60571b.png)
I validated this with Apache Jena's riot; it will correctly read both versions.

_But_ considering this is a pretty printing functionality, extraneous escaping should be removed I think, so I'll reopen this issue.

**Comment by ijdickinson** [comment]
Thanks for the analysis. After thinking about this a bit more, I think I probably **don't** want hyphenated localnames in my data, so I think I'm going to fix that in the generator code. So I understand you want to fix the owl-cli pretty printer, but I think in this case the bigger problem is with my data. 

Which is a slightly long-winded way of saying this isn't an urgent fix for me :smile:

**Comment by atextor** [comment]
Yes, I wanted to fix this in owl-cli (and the underlying [turtle-formatter](https://github.com/atextor/turtle-formatter) library), and I've actually already done so; owl-cli [1.2.2](https://github.com/atextor/owl-cli/releases/tag/v1.2.2) which contains the fix is available since this morning (CET) 😉.
I think the pretty printer should not escape them in any case if it's not necessary.
